#ifndef AUTOCORRELATIONCUDA_DEFINITIONS
#define AUTOCORRELATIONCUDA_DEFINITION


namespace AutocorrelationCUDA {

#define SENSORS 64
#define SENSORS_PER_BLOCK 8
#define GROUPS_PER_SENSOR 5
#define GROUP_SIZE 32
#define REPETITIONS 20
#define INSTANTS_PER_PACKET 100


#define ACC_POS_START (SENSORS_PER_BLOCK * GROUPS_PER_SENSOR * GROUP_SIZE)
#define ZERO_DELAY_START (ACC_POS_START + SENSORS_PER_BLOCK * GROUPS_PER_SENSOR)
#define SHARED_MEMORY_REQUIRED (SENSORS_PER_BLOCK * GROUPS_PER_SENSOR * GROUP_SIZE + SENSORS_PER_BLOCK * GROUPS_PER_SENSOR + SENSORS_PER_BLOCK * GROUPS_PER_SENSOR + SENSORS_PER_BLOCK * GROUPS_PER_SENSOR * GROUP_SIZE * 4)
#define MAX_LAG (GROUPS_PER_SENSOR * GROUP_SIZE)


using uint8 = std::uint_fast8_t;
using uint16 = std::uint_fast16_t;
using uint32 = std::uint_fast32_t;

}


#endif 

